# Lesson 0: Python Crash Course

The first lines in any code I'll be writing for this class are those that import the libraries I'll be using.

In [1]:
import numpy # imports the array library
from matplotlib import pyplot # imports the plotting library

To use a function from one of these libraries we must call the library first followed by a period and then the function.

I'll demonstrate by using the linspace(start,end,number of points) function which creates an array with equally spaced numbers between the start and end. This function is practical for making grids or other bases for plotting.

In [2]:
myarray = numpy.linspace(0,5,10)
print(myarray)

[ 0.          0.55555556  1.11111111  1.66666667  2.22222222  2.77777778
  3.33333333  3.88888889  4.44444444  5.        ]


** Additional notes about Python **
* doesn't require explicitely declared variable types
* operations between floats and integers produces a float
* uses whitespace to group statements together (as opposed to brackets)
* uses a zero-based index

In [3]:
for i in range(5):
    print("Hi \n")

# range function gives a list from an arithmetic progression

Hi 

Hi 

Hi 

Hi 

Hi 



** Slicing Arrays: ** how to look at portions of arrays using NumPy


In [4]:
myvals = numpy.array([1,2,3,4,5])
myvals

array([1, 2, 3, 4, 5])

In [5]:
myvals[0:3]

array([1, 2, 3])

** Note: ** The slice in inclusive on the front end and exclusive on the back

** Assigning array variables **

In [6]:
a = numpy.linspace(1,5,5)
a

array([ 1.,  2.,  3.,  4.,  5.])

In [7]:
b = a
c = a.copy()

In [8]:
a[2] = 17

In [9]:
a

array([  1.,   2.,  17.,   4.,   5.])

In [10]:
b

array([  1.,   2.,  17.,   4.,   5.])

In [11]:
c

array([ 1.,  2.,  3.,  4.,  5.])

When assigning variable b, Python creates an alias called b and routes to a. When values are changed in a, then the changes are reflected in b. If we want a true copy, we have to tell Python to make one.